# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entityTable
  id: FillLockerDetectiveHardsuit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitDetective
    - id: ClothingMaskBreath

