# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerSuit
  name: Security Officer Suit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerModSuit
  name: Security Officer ModSuit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanHosModSuit
  name: Head Of Security ModSuit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanHoSSuit
  name: Head Of Security Suit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanWardenSuit
  name: Warden Suit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanBrigmedicSuit
  name: Brigmedic Suit
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerBulletproofArmorHelmet
  name: Security Officer Bulletproof Armor
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerRiotArmorHelmet
  name: Security Officer Riot Armor
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerReflectiveArmorHelmet
  name: Security Officer Reflective Armor
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanSecurityOfficerBasicArmorHelmet
  name: Security Officer Basic Armor
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanHos
  name: Head Of Security
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanBrigmedic
  name: Brigmedic
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHumanSecurityBase
  id: MobHumanWarden
  name: Warden
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard

- type: entity
  categories: [ ]
  parent: MobHuman
  id: MobHumanSecurityBase
  name: Security Base
  suffix: DEBUG
  components:
  - type: RandomMetadata
    nameSegments:
    - NamesFirst
    - NamesLast
    nameFormat: name-format-standard
  - type: AutoImplant
    implants:
    - MindShieldImplant
