# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  abstract: true
  parent: [ BaseSkillChip, BaseSecurityContraband ]
  id: BaseSkillChipSecurity
  components:
  - type: KnowledgeGrantOnWear
    skills:
      SkillUnarmed: 25
      # NT basic training
      # batoong and laser focused, with some alt weapons, the rest is just to be better than tiders
      SkillMaces: 40
      SkillKnives: 30
      SkillSwords: 20
      SkillPolearms: 20

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipHeadOfSecurity
  name: skill chip (HOS)
  components:
  - type: KnowledgeGrantOnWear
    skills:
      SkillUnarmed: 60
      SkillMaces: 60

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipBrigmedic
  name: skill chip (brigmedic)
  components:
  - type: KnowledgeGrantOnWear
    skills:
      SkillMedicine: 50
      SkillMaces: 5 # actual self defence only chud

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipDetective
  name: skill chip (detective)
  components:
  - type: KnowledgeGrantOnWear
    skills:
      SkillMaces: 20 # discourage det actively arresting people
      # TODO: something for detecting

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipSecurityCadet
  name: skill chip (cadet)
  components:
  - type: KnowledgeGrantOnWear
    skills:
      SkillUnarmed: 20
      SkillMaces: 20 # anti raider tech
    # TODO: xp gain boost

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipSecurityOfficer
  name: skill chip (security)

- type: entity
  parent: BaseSkillChipSecurity
  id: SkillChipWarden
  name: skill chip (warden)
  components:
  # TODO: area DRM
  - type: KnowledgeGrantOnWear
    skills:
      SkillUnarmed: 50
      SkillWeaponsmithing: 50
      SkillMedicine: 25 # Brigmedic isn't real
