# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  parent: BaseMachineCircuitboard
  id: PlumbingPumpCircuitboard
  name: liquid pump board
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: PlumbingPump
    stackRequirements:
      Manipulator: 4
      Steel: 5
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  id: EnergyChemDispenserMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: energy chem dispenser machine board
  description: A machine printed circuit board for an energy chem dispenser.
  components:
    - type: Sprite
      state: medical
    - type: MachineBoard
      prototype: EnergyChemDispenser
      stackRequirements:
        Manipulator: 1
        Glass: 5
        Steel: 5
        BSCrystal: 1
      tagRequirements:
        GlassBeaker:
          amount: 2
          defaultPrototype: Beaker

- type: entity
  id: TelecomTransmitterCircuitboard
  parent: BaseMachineCircuitboard
  name: telecommunication transmitter machine board
  description: A machine printed circuit board for an telecommunication transmitter.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: TelecomTransmitter
    stackRequirements:
      Uranium: 15
      Steel: 15
      Cable: 5
